{% set suffix = '-canary' if env.get('CANARY') else '' %}
{% set name = '%s%s' % (service.name, suffix) %}
---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  selector:
    app: {{name}}
  ports:
    - port: 80
      targetPort: http-api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      containers:
      - name: {{name}}
        image: {{build.images["Dockerfile"]}}
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
