---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qotm-ws
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm-ws
    spec:
      containers:
      - name: qotm
        image: datawire/qotm-ws:1
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
